base:
    seed: &seed 42
model:
    type: Llama
    path: /home/gsb/LLMCMed/abase_models/meta-llama/Meta-Llama-3-8B
    # path: /home/gsb/datasets/precessed/wikitext/wikitext-2-v1
    torch_dtype: auto
calib:
    name: wikitext2
    download: True
    n_samples: 128
    path: /home/gsb/datasets/processed/wikitext/wikitext-2-v1
    # path: /home/gsb/datasets/temp/wikitext/wikitext-2-v1/test-00000-of-00001.parquet
    bs: 1
    seq_len: 2048
    preproc: wikitext2_gptq
    seed: *seed
eval:
    eval_pos: [pretrain, transformed, fake_quant, fake_quant_wo_kv] # 'transformed'; 'fake_quant_wo_kv'; 'pretrain'
    # type: ppl # vqa code 
    name: wikitext2
    download: True
    path: /home/gsb/LLMCMed/adatasets/processed/wikitext/wikitext-2-v1
    bs: 1
    seq_len: 2048
    inference_per_block: False
quant:
    method: GPTQ
    weight:
        bit: 8
        symmetric: True
        granularity: per_group
        group_size: 128
        need_pack: True
        # calib_algo: mse
        # mse_b_num: 2
    special:
        actorder: True
        static_groups: True
        percdamp: 0.01
        blocksize: 128
        true_sequential: True
    quant_out: True
    modality: language
save:
    save_fake: True
    save_trans: True
    # save_trtllm: True
    # trtllm_cfg:
    #     tp_size: 1
    #     pp_size: 1
    # save_mlcllm: True
    save_vllm: True
    # save_sgl: True
    # save_lightllm: True
    
    save_path: /home/gsb/LLMCMed/atrans_models/meta-llama/gptq_w_only_8b_Meta-Llama-3-8B
